package com.reasoningtestgen.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * Test plan generated by LLM before code generation
 * Contains structured plan for test methods, mocks, and assertions
 */
public record TestPlan(
    @JsonProperty("testMethods") List<TestMethodPlan> testMethods,
    @JsonProperty("requiredMocks") List<String> requiredMocks,
    @JsonProperty("requiredImports") List<String> requiredImports,
    @JsonProperty("testStructure") String testStructure,
    @JsonProperty("notes") String notes
) {
    /**
     * Plan for a single test method
     */
    public record TestMethodPlan(
        @JsonProperty("name") String name,
        @JsonProperty("description") String description,
        @JsonProperty("branch") String branch,
        @JsonProperty("givenSetup") String givenSetup,
        @JsonProperty("whenAction") String whenAction,
        @JsonProperty("thenAssertions") List<String> thenAssertions,
        @JsonProperty("isParameterized") boolean isParameterized,
        @JsonProperty("parameterizedData") String parameterizedData
    ) {
        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append("🧪 ").append(name).append("\n");
            sb.append("   📝 ").append(description).append("\n");
            if (isParameterized) {
                sb.append("   🔄 Parameterized: ").append(parameterizedData).append("\n");
            }
            sb.append("   📍 Branch: ").append(branch).append("\n");
            sb.append("   ✅ Assertions: ").append(String.join(", ", thenAssertions)).append("\n");
            return sb.toString();
        }
    }

    /**
     * Format entire plan as readable text
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("📋 TEST GENERATION PLAN\n");
        sb.append("========================\n\n");

        if (testStructure != null && !testStructure.isEmpty()) {
            sb.append("Structure: ").append(testStructure).append("\n\n");
        }

        if (!requiredMocks.isEmpty()) {
            sb.append("🔧 Required Mocks:\n");
            for (String mock : requiredMocks) {
                sb.append("  - @Mock ").append(mock).append("\n");
            }
            sb.append("\n");
        }

        sb.append("📝 Test Methods (").append(testMethods.size()).append("):\n\n");
        for (int i = 0; i < testMethods.size(); i++) {
            sb.append(i + 1).append(". ").append(testMethods.get(i)).append("\n");
        }

        if (!requiredImports.isEmpty()) {
            sb.append("\n📦 Required Imports:\n");
            for (String imp : requiredImports) {
                sb.append("  - ").append(imp).append("\n");
            }
        }

        if (notes != null && !notes.isEmpty()) {
            sb.append("\n📝 Notes: ").append(notes);
        }

        return sb.toString();
    }
}
